name: tests

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Install dependencies
      run: bundle install
    - name: StandardRb check
      run: bundle exec standardrb
    - name: Run tests
      env:
        PADDLE_VENDOR_ID: ${{ secrets.PADDLE_VENDOR_ID }}
        PADDLE_VENDOR_AUTH_CODE: ${{ secrets.PADDLE_VENDOR_AUTH_CODE }}
      run: bundle exec rake